[FEAT] 효과음 전체 List 출력 페이지 구현 + 효과음 필터링 기능 구현
2024-1-CapstoneDesign/ses_website pull request #32
Opened 2024-05-06 07:00 UTC by falconlee236

### 🧐 어떤 것을 변경했어요~?
기존 웹 페이지의 blog로 되어있는 부분에 있는 레이아웃을 전체적으로 변경했습니다.
1. refactoring
  * 기존에 blog로 되어있는 HeadSection 이름 변경
  * 기존에 blog로 되어있는 routing url 변경
  * 기존에 blog로 되어있는 파일 이름 변경
  * 기존에 blog로 되어있는 변수 이름 변경
  * 기존에 blog를 구현할 때 사용하던 더미데이터 삭제
2. soundCard 구현
  * blog카드를 soundCard로 변경
  * blog카드에 있는 이미지 대신에 기존에 만들었던 soundwave 컴포넌트 적용
  * soundwave component에 있는 재생 버튼 위치 변경
  * soundwave component에 별 아이콘 추가
  * soundcard에 tagList 추가
3. 페이지 왼쪽에 sidebar 추가
  * sidebar에 tagList 중 하나를 누르면 필터링 기능까지 구현
  * sidebar위에 있는 라이센스 필터링은 값이 존재한다면 구현할 예정

### 🤔 그렇다면, 어떻게 구현했어요~?
1. refactoring
   해당 템플릿에 있는 모든 blog가 들어간 부분의 변수, 파일이름, url주소 모두 변경
2. soundCard
   기존 blogCard부분에 새로운 UI 추가, 기존 UI 삭제
3. sidebar
  전부 새로 만들었음. Main에서 먼저 서버에서 보내주는 전체 soundList를 이용함.  
  해당 soundList에서 tagList를 전체 뽑아낸다음, javascript의 set을 사용해서 중복 제거,  
  useState함수를 이용해서 필터링 이벤트가 발생했을 때, 상태를 관리하는 로직을 이용해서 필터링 기능 구현

### ❤️‍🔥 당신이 생각하는 PR포인트, 내겐 매력포인트.
* 필터링 한번 체험 해보면 좋을것 같습니다.
* 그리고 웹 사이트 테스트 해보려면 이 레포지토리 클론해서 까는 것 추천합니다.

### 📸 스크린샷, 없으면 이것 참,, 섭섭한데요?
soundList page
<img width="565" alt="image" src="https://github.com/2024-1-CapstoneDesign/ses_website/assets/52999093/c4cf7d68-4377-4bcc-99b2-7d0651009893">

세부 soundListPage (디자인 대기중 @hayeongKo )
<img width="1103" alt="image" src="https://github.com/2024-1-CapstoneDesign/ses_website/assets/52999093/2229d61b-a882-4d12-bb27-800d6a744d37">

필터링 적용
<img width="1114" alt="image" src="https://github.com/2024-1-CapstoneDesign/ses_website/assets/52999093/74d08814-afa0-4d82-b5f5-a33ea2d97d95">

2024-05-06 07:09 UTC, falconlee236 commented
버그 수정중이라 잠시만요 고치고 다시 돌아올게요
제가 확인하라고 하면 그때 다시 리뷰하면 됩니다.

2024-05-06 07:29 UTC, falconlee236 commented
버그 수정 완료했고, 다시 리뷰 하시면 됩니당

2024-05-07 04:06 UTC, hayeongKo approved these changes
수고하셨습니당 (👍🏻 ˃ ᴗ ˂ )👍🏻

2024-05-07 04:38 UTC, hayeongKo requested changes
- soundeffect list에서 파형 배경색 없애주세요 !

2024-05-07 18:03 UTC, falconlee236 commented
<img width="1434" alt="image" src="https://github.com/2024-1-CapstoneDesign/ses_website/assets/52999093/801f408b-3ddd-43a1-b53e-0c479d79d004">
수정 완료 했습니다!
@hayeongKo

2024-05-08 05:06 UTC, hayeongKo approved these changes
확인했습니다 !-!

2024-05-08 05:10 UTC, merged